### ISSUE TITLE
Nothing in Add-in page

### ISSUE THREAD

**Issue by lyhbuaa** [dnilsson1/G-codeToRapid#2]
I'm running the software, but I don't get anything in robotStudio's add-in page
![test](https://user-images.githubusercontent.com/16487983/101791485-8a588400-3b3e-11eb-8541-2b3f8a1084c1.jpg)

**Comment by dnilsson1** [comment]
No, that is because the menu bar components have been updated since the code was written. You have to check for the deprecated method calls and update them according to the documentation found at https://developercenter.robotstudio.com/api/robotstudio/

Sorry, that I haven't had the time to update the code. The repo is mainly there as a code source for the paper since I had a bit too many requests by email that wanted me to send the code. 

Best regards,
Daniel

**Comment by dnilsson1** [comment]
The code has now been updated and the add-in should now be able to run. As well as show up in the add-in section.

**Comment by lyhbuaa** [comment]
Thank you very much！
